services:
  pg:
    image: postgres:18.1-alpine
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  minio:
    image: quay.io/minio/minio:RELEASE.2023-09-07T02-05-02Z
    restart: unless-stopped
    command: server /data --address ":9000" --console-address ":9090"
    ports:
      - "9001:9000"
      - "9091:9090"
    env_file:
      - ../.env
    volumes:
      - ./data/minio:/data

volumes:
  postgres_data: